# Generated by Django 2.0.3 on 2018-03-13 04:56

import concurrency.fields
from django.db import migrations, models
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('publish', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('body', markdownx.models.MarkdownxField()),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bulletin',
                'verbose_name_plural': 'bulletins',
                'ordering': ['-published'],
            },
        ),
    ]
