# Generated by Django 2.1.5 on 2019-02-10 21:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=64, unique=True, verbose_name='name')),
                (
                    'service',
                    models.CharField(
                        choices=[
                            ('discord', 'Discord'),
                            ('battle_net_us', 'Battle.net US'),
                            ('eve_online', 'EVE Online'),
                        ],
                        max_length=64,
                        verbose_name='service',
                    ),
                ),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('client_id', models.CharField(max_length=191, verbose_name='client id')),
                ('client_secret', models.CharField(max_length=191, verbose_name='client secret')),
                ('scope_override', models.TextField(blank=True, default='', verbose_name='scope override')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, verbose_name='key')),
                ('tag', models.CharField(blank=True, default='', max_length=64, verbose_name='tag')),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='oauth2.Client', verbose_name='client'
                    ),
                ),
                (
                    'users',
                    models.ManyToManyField(
                        related_name='resources',
                        related_query_name='resource',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='users',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('token_type', models.CharField(default='bearer', max_length=64, verbose_name='token type')),
                ('access_token', models.TextField(verbose_name='access token')),
                ('refresh_token', models.TextField(blank=True, default='', verbose_name='refresh token')),
                ('expires_in', models.PositiveIntegerField(blank=True, null=True, verbose_name='expires in')),
                ('scope', models.TextField(blank=True, default='', verbose_name='scope')),
                ('redirect_uri', models.URLField(blank=True, default='', verbose_name='redirect URI')),
                (
                    'resource',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='oauth2.Resource', verbose_name='resource'
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(name='resource', unique_together={('client', 'key')}),
    ]
