# Generated by Django 2.1.4 on 2018-12-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='scope_override',
            field=models.TextField(blank=True, default='', verbose_name='scope override'),
        ),
    ]
