# Generated by Django 2.1.5 on 2019-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='redirect_uri',
            field=models.URLField(blank=True, default='', verbose_name='redirect URI'),
        ),
        migrations.AddField(
            model_name='token',
            name='scope',
            field=models.TextField(blank=True, default='', verbose_name='scope'),
        ),
    ]
