language: python
dist: xenial
sudo: true

python:
  - 3.7

env:
  global:
    - DJANGO_SETTINGS_MODULE="umami.settings"
    - PIP_USE_MIRRORS=true
    - DATABASE_URL=sqlite:///db.sqlite3

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --user poetry==1.0.0a2 codecov
  - poetry install
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput

script:
  - pytest --cov

after_success: codecov

notifications:
    email:
        on_success: change
        on_failure: always
