language: python
dist: xenial
sudo: true

python:
  - 3.7

env:
  global:
    - DJANGO="2.1"
    - DJANGO_SETTINGS_MODULE="umami.settings"
    - PIP_USE_MIRRORS=true
    - DATABASE_URL=sqlite:///db.sqlite3

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install pipenv
  - pipenv install --dev
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput

script:
  - pipenv run pytest

after_success: coveralls

notifications:
    email:
        on_success: change
        on_failure: always
