# Generated by Django 2.0.7 on 2018-07-16 02:48

import concurrency.fields
from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('adapter', models.CharField(choices=[('discord', 'Discord'), ('battle_net', 'Battle.net'), ('eve_online', 'EVE Online')], max_length=50, verbose_name='adapter')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('client_id', models.CharField(max_length=191, verbose_name='client id')),
                ('client_secret', models.CharField(max_length=191, verbose_name='client secret')),
                ('options', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='options')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('adapter', models.CharField(choices=[('discord', 'Discord'), ('battle_net', 'Battle.net'), ('eve_online', 'EVE Online')], max_length=50, verbose_name='adapter')),
                ('name', models.CharField(max_length=191, verbose_name='name')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clientscope',
            unique_together={('adapter', 'name')},
        ),
        migrations.AddField(
            model_name='client',
            name='scopes',
            field=models.ManyToManyField(related_name='clients', to='guildmaster.ClientScope', verbose_name='scopes'),
        ),
        migrations.CreateModel(
            name='BattleNetClient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('guildmaster.client',),
        ),
        migrations.CreateModel(
            name='DiscordClient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('guildmaster.client',),
        ),
        migrations.CreateModel(
            name='EveOnlineClient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('guildmaster.client',),
        ),
    ]
