# Generated by Django 2.1.7 on 2019-03-17 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guildmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAccount',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('discriminator', models.CharField(max_length=4, verbose_name='dsicriminator')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='MFA enabled')),
                ('avatar', models.CharField(blank=True, default='', max_length=64, verbose_name='avatar')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guildmaster.Resource', verbose_name='oauth2 resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('username', 'discriminator'),
            },
        ),
    ]
