# Generated by Django 2.2 on 2019-04-24 14:25

import uuid

import concurrency.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('guildmaster', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'version',
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text='record revision number', verbose_name='entity version'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                (
                    'users',
                    models.ManyToManyField(
                        related_name='accounts',
                        related_query_name='account',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='users',
                    ),
                ),
            ],
        )
    ]
