# Generated by Django 2.2.4 on 2019-08-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('guildmaster', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='token',
            name='resource_tag',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='resource tag'),
        ),
        migrations.AlterField(
            model_name='client',
            name='provider_id',
            field=models.CharField(
                choices=[('discord', 'Discord'), ('battle-net-us', 'Battle.net US')],
                max_length=64,
                unique=True,
                verbose_name='providers',
            ),
        ),
    ]
