# Generated by Django 2.2 on 2019-04-24 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('guildmaster', '0002_account')]

    operations = [
        migrations.CreateModel(
            name='DiscordAccount',
            fields=[
                (
                    'account_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to='guildmaster.Account',
                    ),
                ),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('discriminator', models.CharField(max_length=4, verbose_name='dsicriminator')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='MFA enabled')),
                ('avatar', models.CharField(blank=True, default='', max_length=64, verbose_name='avatar')),
            ],
            options={'ordering': ('username', 'discriminator')},
            bases=('guildmaster.account',),
        )
    ]
