# Generated by Django 2.0.7 on 2018-07-16 01:58

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guildmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveOnlineClient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('guildmaster.client',),
        ),
    ]
